blank_issues_enabled: true
contact_links:
  - name: ğŸŒ Community Slack
    url: https://launchpass.com/littlehorsecommunity/free
    about: Join our Community Slack to get real time support and connect with other LittleHorse users!