blank_issues_enabled: true
contact_links:
  - name: ğŸŒ Community Slack
    url: [link to create bug report]
    about: Join our Community Slack to get real time support and connect with other LittleHorse users!
  - name: ğŸ’¬ Discussions
    url: https://github.com/littlehorse-enterprises/littlehorse/discussions
    about: Open a discussion! Useful for open-ended conversations and community engagement.